global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:

  - job_name: 'transcendence-app'
    static_configs:
      - targets: ['dev:3000']  # Port de ton app Fastify
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9101']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 10s
    metrics_path: '/_prometheus/metrics'

  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
    scrape_interval: 10s
    metrics_path: '/_node/stats'